name: dmitriy_krutikov

on:
    push:
        branches: ["dmitriy_krutikov/task-7"]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.18'
    
        - name: Run unit tests
          working-directory: ./dmitriy.krutikov/task-7
          run: go test -v ./...
