name: kirill_radkin
on:
  push:
    branches: [ "kirill.radkin/task-7" ]

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./kirill.radkin/task-7
          args: --out-format=colored-line-number
  
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.2

      - name: task-7
        working-directory: ./kirill.radkin/task-7
        run: go test -v ./...

