name: ksenia_dobrovolskaia

on:
  push:
    branches: [ "ksenia.dobrovolskaia/task-7" ]

jobs:

  Go-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run equal tests
      working-directory: ./ksenia.dobrovolskaia/task-7
      run: go test -v ./... 
