name: sergei_zimmerman
on:
  push:
    branches: ["sergei.zimmerman/task-7"]
jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            sergei.zimmerman/task-7
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22.2
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          working-directory: ./sergei.zimmerman/task-7
      - working-directory: ./sergei.zimmerman/task-7
        run: go test -v ./... -coverprofile cover.out
