name: timur_golubovich

on:
  push:
    branches: [ "tg-sc/task-7" ]

jobs:

  Go-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24.0

    - name: Set up mockery
      working-directory: ./timur.golubovich/task-7
      run: go install github.com/vektra/mockery/v2@latest

    - name: Generate mock files
      working-directory: ./timur.golubovich/task-7
      run: go generate ./... && go mod tidy

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.6
        working-directory: ./timur.golubovich/task-7
        run: golangci-lint run

    - name: Run tests
      working-directory: ./timur.golubovich/task-7
      run: go test -v ./...
